--name:ObtenerTodo
SELECT * FROM PRODUCTO;

--name:obtenerPorID
SELECT * FROM PRODUCTO WHERE ID = $1

--name:crear
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, DESCRIPCION)
VALUES $1,$2,$3;

--name:borrarPorID
DELETE FROM PRODUCTO WHERE ID = $1;